=== albumeers/stamp-pagegen/src/main/resources/pagegen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2012 Jason Drake (jadrake75@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!ELEMENT album (page|title-page)+>
<!ELEMENT page (set|column-set)*>
<!ELEMENT title-page (content-items) >
<!ELEMENT column-set (set+)>
<!ELEMENT set (comp-set|row-set)*>
<!ELEMENT comp-set (row-set+)>
<!ELEMENT row-set (s|set-tenant)*>
<!ELEMENT set-tenant (s+)>
<!ELEMENT content-items (item)*>
<!ELEMENT item (#PCDATA)>
<!ELEMENT s (#PCDATA)>

<!ATTLIST page 
			title 		CDATA #IMPLIED
			subtitle 	CDATA #IMPLIED
			classifier 	CDATA #IMPLIED
			pagenum		CDATA #IMPLIED
			border          CDATA #IMPLIED >

<!ATTLIST title-page
                        title           CDATA #IMPLIED
                        subtitle        CDATA #IMPLIED
                        image           CDATA #IMPLIED
                        description     CDATA #IMPLIED >
                        
<!ATTLIST set 
		issue 			CDATA #IMPLIED
		description		CDATA #IMPLIED
		description-secondary   CDATA #IMPLIED
		comment 		CDATA #IMPLIED >

<!ATTLIST column-set
                issue CDATA #IMPLIED
		use-box-centering (true|false) #IMPLIED
                spacing (high|low|box) #IMPLIED >

<!ATTLIST comp-set
		description CDATA #IMPLIED 
                spacing (high|low|box) #IMPLIED >
				
<!ATTLIST row-set  
		description	CDATA #IMPLIED
                spacing-horizontal CDATA #IMPLIED
		valign (top|middle|bottom) #IMPLIED >

<!ATTLIST set-tenant
		orientation (vertical|horizontal) #IMPLIED
                border (true|false) #IMPLIED >

<!ATTLIST s	
		image CDATA #IMPLIED
		image-only (true|false) #IMPLIED
		bisect (vertical|top_right|top_left|none) #IMPLIED
                border (true|false) #IMPLIED
		shape (rectangle|triangle|diamond) #IMPLIED >

=== albumeers/stamp-pagegen/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE album SYSTEM "../classes/pagegen.dtd">
 <album>
 <page title="Indian States" subtitle="Barwani">
  	
 	<column-set>
 	<set issue="1910-40" description="01.01.1910: Portrait of King George V\nWatermarked Crown and &apos;CA&apos;"
 		description-secondary="Die I">
 		<row-set>
 			<s image="images/symbol.png">"21 25","1/4d","green and red","","23"</s>
 			<s>"21 25" "1/4d" "blue-green" "" "23a"</s>
 			<s>"21 25" "1/4d" "green" "(R)" "24"</s>
 			<s>"21 25" "1/2d" "green" "" "25"</s>
 		</row-set>
 	</set>
 	<set issue="1914" description="Portrait of King George V\nOverprinted &apos;POSTAGE&apos;">
 		<row-set>
 			<s>"21 24","1/4d","green","(R)","24"</s>
 		</row-set>
 	</set>
 	</column-set>
	<set issue="1914-40" description="">
 		<row-set>
 			<s shape="triangle">"45 25","1/4d","green","(R)","24"</s>
 		</row-set>
 	</set>
 	<set issue="1914-40" description="">
 		<row-set>
 			<s shape="rectangle">"21 25","1/4d","green","(R)","24"</s>
 		</row-set>
 	</set>
 	<set issue="1914-40" description="">
 		<row-set>
 			<s shape="diamond">"25 25","1/4d","green","(R)","24"</s>
 		</row-set>
 		<row-set>
 		<s>"21 25" "1/2d" "blue-green" "" "5c"</s>
 		</row-set>
 	</set>
 </page>
 <page title="Indian States" subtitle="Barwani" classifier="Official Stamps" border="true">
 	<column-set>
 	<set issue="1910-40" description="01-01-1910: Barwani stamps of King shi shi foo foo\nWatermarked Crown and &apos;CA&apos;">
 		<comp-set>
 			<row-set description="Perforated 11">
 				<s>"39 41","1/4d","green","(R)","O1"</s>
 			</row-set>
 			<row-set description="Perforated 12">
 				<s>"39 41","2c","red","(R)","O2"</s>
 			</row-set>
 		</comp-set>
 	</set>
 	<set issue="1914" description="some descriptionription">
 		<row-set>
 			<s>"39 41","1/4d","green","(R)","O1"</s>
 		</row-set>
 	</set>
 	</column-set>
 	<set issue="1914-40" description="">
 		<row-set>
 			<s>"39 41","1/4d","green","(R)","O1"</s>
 		</row-set>
 	</set>
 </page>
 </album>

=== albumeers/stamp-pagegen/src/test/resources/title-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE album SYSTEM 'http://www.drakeserver.com/dtds/pagegen.dtd'>

<album>
    <title-page title="Japan" subtitle="(Nippon)" description="Country on the island in the Pacific" image="japan-seal2.png">
        <content-items>
            <item>Empire of Japan (-1975)</item>
            <item>Offices in China</item>
            <item>Offices in Korea</item>
        </content-items>
    </title-page>
    <title-page title="Germany" description="Country in the middle of Europe" image="germany-seal2.png">
        <content-items>
            <item>Empire of Germany (-1919)</item>
            <item>Third Reich (-1945)</item>
            <item>West Germany (1945-1975)</item>
        </content-items>
    </title-page>
    <title-page title="Germany" description="Country in the middle of Europe" image="germany-seal.png">
        <content-items>
            <item>Empire of Germany (-1919)</item>
            <item>Third Reich (-1945)</item>
            <item>West Germany (1945-1975)</item>
        </content-items>
    </title-page>
    <title-page title="Vatican City" subtitle="Guy with Pointy Hat is King" description="Whatever possessed me to create pages for this?\nI really don't know">
    </title-page>
    <page subtitle="Test without Title">
        
    </page>
    
</album>
